custom: ["https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api#donate",
         "https://www.lucit.co/desktop-and-server-apps.html",
         "https://www.lucit.co/desktop-und-server-programme.html"]
