name: Feature request
description: Suggest an idea for this library.
labels: enhancement 
assignees:
  - oliver-zehentleitner
body:
  - type: markdown
    attributes:
      value: |
        Please post here only issues concerning this repository and follow the [Issue-Guidelines](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-suite/wiki/Issue-Guidelines). 
        
        Most of these fields are not mandatory, but please provide as much information as possible.
  - type: textarea
    id: Problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: 
    validations:
      required: false
      
  - type: textarea
    id: Solution
    attributes:
      label: Describe the solution you'd like.
      description: |
        A clear and concise description of what you want to happen.
      placeholder: 
    validations:
      required: false

  - type: textarea
    id: Alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
      placeholder: 
    validations:
      required: false

  - type: textarea
    id: Additional
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
      placeholder: 
    validations:
      required: false

