name: Build and Publish GH+PyPi

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ubuntu-latest  # Ändern zu ubuntu-latest, da wir Docker verwenden
    strategy:
      matrix:
        os: [ "manylinux2014_aarch64" ]  # Zielplattform für ARM-Architektur
    services:
      docker:
        image: docker://multiarch/qemu-user-static:latest
        options: --privileged
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS_LINUX: aarch64  # Setzen der Architektur auf ARM64
          CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux2014_aarch64  # Verwenden des manylinux-Images für ARM64
          CIBW_SKIP: "*-win32 *-manylinux_i686 *-macosx_* *-manylinux_x86_64"  # Überspringen nicht relevanter Builds

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  Release:
    needs: [ build_wheels, build_sdist ]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: write
      discussions: write
      id-token: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Please read the [CHANGELOG](https://github.com/LUCIT-Systems-and-Development/unicorn-fy/blob/master/CHANGELOG.md) for further information.
          discussion_category_name: releases
          draft: false
          files: |
            dist/*.tar.gz
            dist/*.whl
          generate_release_notes: true
          name: unicorn-fy
          prerelease: false
          tag_name: 0.13.1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PyPi Release
        uses: pypa/gh-action-pypi-publish@release/v1